version: '3'
services:
  halo:
    image: halohub/halo:1.5.6                
    container_name: halo              
    restart: unless-stopped                                       # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                            # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./halo:/root/.halo"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      - "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "LC_ALL=en_US.UTF-8"
      - "JAVA_VERSION=jdk-11.0.11+9"
      - "JAVA_HOME=/opt/java/openjdk"
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "JVM_OPTS=-Xmx256m -Xms256m"
      - "TZ=Asia/Shanghai"
    ports:                              # 映射端口
      - "8090:8090"
    privileged: true #  使用该参数，container内的root拥有真正的root权限。
    networks:
      - ap
networks:
  ap:
    external: true
