version: '3'
services:
  oap-server:
    #image: apache/skywalking-oap-server:9.2.0
    image: registry.cn-shenzhen.aliyuncs.com/whiteblog/skywalking-oap-server-mysql:9.2.0
    container_name: skywalking-oap-server
    ports:
      - 11800:11800 # 数据采集接口
      - 12800:12800  # ui通信接口
    environment:
      - SW_STORAGE=mysql
      - SW_JDBC_URL=jdbc:mysql://192.168.1.25:3306/skywalking?rewriteBatchedStatements=true
      - SW_DATA_SOURCE_USER=aa
      - SW_DATA_SOURCE_PASSWORD=bb
    volumes:
      - ./config:/skywalking/config
    #      - ./oap-libs:/skywalking/oap-libs
    networks:
      - ap


  ui:
    image: apache/skywalking-ui:9.2.0
    container_name: skywalking-ui
    ports:
      - 18080:8080
    environment:
      - SW_OAP_ADDRESS=oap-server:12800
    depends_on:
      - oap-server
    networks:
      - ap

networks:
  ap:
    driver: bridge