version: '3.1'
services:
  mysql:
    image: registry.cn-shenzhen.aliyuncs.com/whiteblog/mysql #mysql8.0.30
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: peiqi666
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - ./mysql8.0/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql8.0/data:/var/lib/mysql
      - ./mysql8.0/init/:/docker-entrypoint-initdb.d/
    networks:
      - ap
networks:
  ap:
    external: true