version: '3'
services:
  seata-server:
    image: seataio/seata-server:1.5.2
    container_name: seata
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
      - SEATA_IP=seata_ip
      - SEATA_PORT=8091
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"    # 设置系统时区
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"    # 设置时区
      - "./resources:/seata-server/resources"
